[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:vncserver]
command=/usr/bin/vncserver :1 -geometry 1280x800 -depth 24 -localhost no -SecurityTypes VncAuth -xstartup /home/ubuntu/.vnc/xstartup
autorestart=true
user=ubuntu
environment=DISPLAY=:1,HOME=/home/ubuntu

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5901
autorestart=true
user=ubuntu
